spring:
  application:
    name: menu-planner
  graphql:
    path: /graphql
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://spring:5432/meal_planner
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


---

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/meal_planner
