name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
      actions: read
      checks: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.JIB_TOKEN }}

      - name: Build and Push Docker image with Jib
        if: github.event_name != 'pull_request'
        run: |
          mvn -B jib:build \
          -Djib.to.auth.username=${{ github.repository_owner }} \
          -Djib.to.auth.password=${{ secrets.JIB_TOKEN }} \
          --file pom.xml

      - name: Build Docker image with Jib (without pushing)
        if: github.event_name == 'pull_request'
        run: mvn -B jib:dockerBuild --file pom.xml